app/petereport/urls.py
"""petereport URL Configuration

"""

from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from preport.views import markdown_uploader

urlpatterns = [
    # Needed for locale change
    path('i18n/', include('django.conf.urls.i18n')),
    path('martor/', include('martor.urls')),
    path('api/uploader/', markdown_uploader, name='markdown_uploader'),
]

urlpatterns += i18n_patterns(
    path('', include('preport.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ADMIN_ENABLED:
    from django.contrib import admin
    urlpatterns += [
        path('admin/', admin.site.urls)
    ]

app/preport/urls.py
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    # Auth
    path('accounts/', include('django.contrib.auth.urls')),
    # Users
    path('configuration/users/', views.user_list, name='user_list'),
    path('configuration/user/add', views.user_add, name='user_add'),
    path('configuration/user/edit/<int:pk>', views.user_edit, name='user_edit'),
    path('configuration/user/delete/', views.user_delete, name='user_delete'),
    # Settings
    path('configuration/settings/', views.settings, name='settings'),
    # Customers
    path('customer/list/', views.customer_list, name='customer_list'),
    path('customer/add/', views.customer_add, name='customer_add'),
    path('customer/edit/<int:pk>', views.customer_edit, name='customer_edit'),
    path('customer/delete/', views.customer_delete, name='customer_delete'),
    path('customer/view/<int:pk>', views.customer_view, name='customer_view'),
    # Products
    path('product/list/', views.product_list, name='product_list'),
    path('product/add/', views.product_add, name='product_add'),
    path('product/edit/<int:pk>', views.product_edit, name='product_edit'),
    path('product/delete/', views.product_delete, name='product_delete'),
    path('product/view/<int:pk>', views.product_view, name='product_view'),
    # Reports
    path('report/list/', views.report_list, name='report_list'),
    path('report/add/', views.report_add, name='report_add'),
    path('report/view/<int:pk>', views.report_view, name='report_view'),
    path('report/edit/<int:pk>', views.report_edit, name='report_edit'),
    path('report/delete/', views.report_delete, name='report_delete'),
    path('report/duplicate/', views.report_findings_duplicate, name='report_findings_duplicate'),
    path('report/uploadsummaryfindings/<int:pk>', views.uploadsummaryfindings, name='uploadsummaryfindings'), # prepend a language code in ajax
    path('report/download/markdown/<str:template>/<int:pk>', views.reportdownloadmarkdown, name='reportdownloadmarkdown'),
    path('report/download/html/<str:template>/<int:pk>', views.reportdownloadhtml, name='reportdownloadhtml'),
    path('report/download/pdf/<str:template>/<int:pk>', views.reportdownloadpdf, name='reportdownloadpdf'),
    path('report/download/jupyter/<str:template>/<int:pk>', views.reportdownloadjupyter, name='reportdownloadjupyter'),
    # Findings
    path('report/findings/<int:pk>', views.reportfindings, name='reportfindings'),
    path('finding/add/<int:pk>', views.finding_add, name='finding_add'),
    path('finding/edit/<int:pk>', views.finding_edit, name='finding_edit'),
    path('finding/delete/', views.finding_delete, name='finding_delete'),
    path('finding/view/<int:pk>', views.finding_view, name='finding_view'),
    path('findings/open/', views.openfindings, name='openfindings'),
    path('findings/closed/', views.closedfindings, name='closedfindings'),
    path('findings/csv/<int:pk>', views.downloadfindingscsv, name='downloadfindingscsv'),
    path('findings/upload/<int:pk>', views.upload_csv_findings, name='upload_csv_findings'),
    path('findings/defectdojo/products/<int:pk>', views.defectdojo_products, name='defectdojo_products'),
    path('findings/defectdojo/import/<int:pk>/<int:ddpk>', views.defectdojo_import, name='defectdojo_import'),
    path('findings/defectdojo/viewfindings/<int:pk>/<int:ddpk>', views.defectdojo_viewfindings, name='defectdojo_viewfindings'),
    path('findings/defectdojo/import_finding/<int:pk>/<int:ddpk>', views.defectdojo_import_finding, name='defectdojo_import_finding'),
    path('finding/duplicate/', views.finding_duplicate, name='finding_duplicate'),
    # Custom Fields
    path('field/add/<int:pk>', views.field_add, name='field_add'),
    path('finding/customfields/<int:pk>', views.fields, name='fields'),
    path('field/delete/', views.field_delete, name='field_delete'),
    path('field/edit/<int:pk>', views.field_edit, name='field_edit'),
    # Appendix
    path('report/appendix/<int:pk>', views.reportappendix, name='reportappendix'),
    path('appendix/add/<int:pk>', views.appendix_add, name='appendix_add'),
    path('appendix/view/<int:pk>', views.appendix_view, name='appendix_view'),
    path('appendix/delete/', views.appendix_delete, name='appendix_delete'),
    path('appendix/edit/<int:pk>', views.appendix_edit, name='appendix_edit'),
    # Templates
    path('template/list/', views.template_list, name='template_list'),
    path('template/add/', views.template_add, name='template_add'),
    path('template/add/finding/<int:pk>', views.templateaddfinding, name='templateaddfinding'),
    path('template/add/report/<int:pk>/<int:reportpk>', views.templateaddreport, name='templateaddreport'),
    path('template/view/<int:pk>', views.template_view, name='template_view'),
    path('template/delete/', views.template_delete, name='template_delete'),
    path('template/edit/<int:pk>', views.template_edit, name='template_edit'),
    # CWE
    path('cwe/list/', views.cwe_list, name='cwe_list'),
    path('cwe/add/', views.cwe_add, name='cwe_add'),
    path('cwe/edit/<int:pk>', views.cwe_edit, name='cwe_edit'),
    path('cwe/delete/', views.cwe_delete, name='cwe_delete'),
    # OWASP
    path('owasp/list/', views.owasp_list, name='owasp_list'),
    path('owasp/add/', views.owasp_add, name='owasp_add'),
    path('owasp/edit/<int:pk>', views.owasp_edit, name='owasp_edit'),
    path('owasp/delete/', views.owasp_delete, name='owasp_delete'),
    # Attack Flows
    path('report/attackflow/<int:pk>', views.reportattackflow, name='reportattackflow'),
    path('attackflow/add/<int:pk>', views.attackflow_add, name='attackflow_add'),
    path('attackflow/add_flow/<int:pk>/<int:finding_pk>', views.attackflow_add_flow, name='attackflow_add_flow'),
    path('attackflow/edit/<int:pk>', views.attackflow_edit_flow, name='attackflow_edit_flow'),
    path('attackflow/add_afb/<int:pk>/<int:finding_pk>', views.attackflow_add_afb, name='attackflow_add_afb'),
    path('attackflow/edit_afb/<int:pk>', views.attackflow_edit_afb, name='attackflow_edit_afb'),
    path('attackflow/delete/', views.attackflow_delete, name='attackflow_delete'),
    # Deliverables
    path('deliverable/list/', views.deliverable_list, name='deliverable_list'),
    path('deliverable/delete/', views.deliverable_delete, name='deliverable_delete'),
    path('deliverable/download/<int:pk>', views.deliverable_download, name='deliverable_download'),
]

app/preport/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from martor.models import MartorField

import datetime
import re

import pathlib

cvss_regex = re.compile('.+ \((CVSS:.+)\)$')


# ---------- CWE ------------

class DB_CWE(models.Model):
	cwe_id = models.IntegerField(blank=False, unique=True)
	cwe_name = models.CharField(max_length=255, blank=True)
	cwe_description = models.TextField(blank=True)
	class Meta:
		verbose_name_plural = "CWEs"
	def __str__(self):
		return str(self.cwe_id)
	def get_label (self):
		return "%s - %s" % (self.cwe_id, self.cwe_name)
	
# ---------- OWASP ------------

class DB_OWASP(models.Model):
	owasp_id = models.IntegerField(blank=False, unique=True)
	owasp_year = models.IntegerField(blank=False, unique=False)
	owasp_name = models.CharField(max_length=255, blank=True)
	owasp_description = models.TextField(blank=True)
	owasp_url = models.CharField(max_length=255, blank=True)
	owasp_full_id = models.CharField(max_length=20, blank=True)
	class Meta:
		verbose_name_plural = "OWASPs"
	def __str__(self):
		return str(self.owasp_id)
	def save(self, *args, **kwargs):
		prefix = 'A'
		if self.owasp_id < 0:
			self.owasp_full_id = "-1"
		elif self.owasp_id < 10:
			prefix += '0'
		self.owasp_full_id = prefix + str(self.owasp_id) + ':' + str(self.owasp_year)
		super().save(*args, **kwargs)
	def get_label (self):
		return "%s - %s" % (self.owasp_full_id, self.owasp_name)

# ---------- Customer ------------

class DB_Customer(models.Model):
	name = models.CharField(max_length=255, blank=False)
	contact = models.EmailField(max_length=255, blank=True)
	description = MartorField(blank=True)
	class Meta:
		verbose_name_plural = "Customers"
	def __str__(self):
		return self.name
	def get_label (self):
		return self.name

# ---------- Settings ------------

def logo_dst(instance, filename):
    return 'images/company_picture{}'.format(pathlib.Path(filename).suffix)

class DB_Settings(models.Model):
	company_name = models.CharField(max_length=255, blank=False)
	company_website = models.CharField(max_length=255, blank=True)
	company_address = models.CharField(max_length=255, blank=True)
	report_subject = models.CharField(max_length=255, blank=True)
	# File will be uploaded to MEDIA_ROOT/images/<filename>
	company_picture = models.ImageField(upload_to=logo_dst, blank=True)

	def save(self, *args, **kwargs):
		if self.__class__.objects.count():
			self.pk = self.__class__.objects.first().pk
		super().save(*args, **kwargs)
	class Meta:
		verbose_name_plural = "Settings"
	def get_label (self):
		return self.company_name


# ---------- Product ------------

class DB_Product(models.Model):
	customer = models.ForeignKey(DB_Customer, default=1, on_delete=models.CASCADE)
	name = models.CharField(max_length=255, blank=False)
	description = MartorField(blank=True)
	class Meta:
		verbose_name_plural = "Products"
	def __str__(self):
		return self.name
	def get_label (self):
		return self.name

# ---------- Report ------------

class DB_Report(models.Model):
	product = models.ForeignKey(DB_Product, on_delete=models.CASCADE)
	report_id = models.CharField(max_length=255, blank=False, unique=True)
	title = models.CharField(max_length=255, blank=False)
	executive_summary_image = models.TextField(blank=True, null=True)
	cwe_categories_summary_image = models.TextField(blank=True)
	owasp_categories_summary_image = models.TextField(blank=True)
	executive_summary = MartorField()
	scope = MartorField()
	outofscope = MartorField()
	methodology = MartorField()
	recommendation = MartorField()
	creation_date = models.DateTimeField(auto_now_add=True)
	report_date = models.DateTimeField(blank=False)
	audit_start = models.DateField(blank=True, null=True)
	audit_end = models.DateField(blank=True, null=True)
	def __str__(self):
		return self.title
	def get_label (self):
		return self.title
	class Meta:
		verbose_name_plural = "Reports"


# ---------- Finding ------------

class DB_Finding(models.Model):
	report = models.ForeignKey(DB_Report, on_delete=models.CASCADE)
	finding_id = models.CharField(blank=True, max_length=200)
	status = models.CharField(blank=True, max_length=200, default="Open")
	creation_date = models.DateTimeField(auto_now_add=True, null=True)
	closed_at = models.DateTimeField(blank=True, null=True)
	title = models.CharField(blank=True, max_length=200)
	severity = models.CharField(blank=True, max_length=200)
	cvss_vector = models.CharField(blank=True, max_length=200)
	cvss_score = models.DecimalField(max_digits=3, decimal_places=1, default=0)
	description = MartorField(blank=True)
	location = MartorField(blank=True)
	impact = MartorField(blank=True)
	recommendation = MartorField(blank=True)
	references = MartorField(blank=True)
	poc = MartorField(blank=True)
	cwe = models.ForeignKey(DB_CWE, on_delete=models.CASCADE, null=True, blank=True)
	owasp = models.ForeignKey(DB_OWASP, on_delete=models.CASCADE, null=True, blank=True)

	def __str__(self):
		return self.title
	def get_label (self):
		return self.title

	def save(self, *args, **kwargs):
		if self.status == "Close":
			self.closed_at = datetime.datetime.now()
		super().save(*args, **kwargs)

	def get_cvss_score_anchor(self):
		m = cvss_regex.search(self.cvss_vector)
		if m:
			return m.group(1)
	class Meta:
		verbose_name_plural = "Findings"


# ---------- Finding templates ------------

class DB_Finding_Template(models.Model):
	finding_id = models.CharField(blank=False, max_length=200)
	title = models.CharField(blank=False, max_length=200)
	severity = models.CharField(blank=True, max_length=200)
	cvss_vector = models.CharField(blank=True, max_length=200)
	cvss_score = models.DecimalField(max_digits=3, decimal_places=1, default=0)
	description = MartorField(blank=True)
	location = MartorField(blank=True)
	impact = MartorField(blank=True)
	recommendation = MartorField(blank=True)
	references = MartorField(blank=True)
	poc = MartorField(blank=True)
	cwe = models.ForeignKey(DB_CWE, on_delete=models.CASCADE, null=True, blank=True)
	owasp = models.ForeignKey(DB_OWASP, on_delete=models.CASCADE, null=True, blank=True)

	def get_label (self):
		return self.title

	def get_cvss_score_anchor(self):
		m = cvss_regex.search(self.cvss_vector)
		if m:
			return m.group(1)



# ---------- Appendix ------------

class DB_Appendix(models.Model):
	finding = models.ManyToManyField(DB_Finding, related_name='appendix_finding', blank=True)
	title = models.CharField(blank=False, max_length=200)
	description = MartorField()
	def get_label (self):
		return self.title


# ---------- Attack Tree ------------

class DB_AttackTree(models.Model):
	finding = models.ManyToManyField(DB_Finding, related_name='attacktree_finding', blank=True)
	title = models.CharField(blank=False, max_length=200)
	attacktree = models.TextField(blank=True, null=True)
	svg_file = models.TextField(blank=True, null=True)
	def get_label (self):
		return self.title

# ---------- Custom Field ------------

class DB_Custom_field(models.Model):
	finding = models.ForeignKey(DB_Finding, related_name='custom_field_finding', blank=True, on_delete=models.CASCADE)
	title = models.CharField(blank=False, max_length=200)
	description = MartorField(blank=True, null=True)

	def get_label (self):
		return self.title

# ---------- Attack Flow ------------

class DB_AttackFlow(models.Model):
	finding = models.ManyToManyField(DB_Finding, related_name='attackflow_finding', blank=True)
	title = models.CharField(blank=False, max_length=200)
	attackflow_afb = models.TextField(blank=True, null=True)
	attackflow_png = models.TextField(blank=True, null=True)
	def get_label (self):
		return self.title


# ---------- Deliverable ------------
class DB_Deliverable(models.Model):
	report = models.ForeignKey(DB_Report, on_delete=models.CASCADE)
	filename = models.CharField(max_length=2048, blank=False, unique=False)
	generation_date = models.DateTimeField(blank=False)
	filetype = models.CharField(max_length=32, blank=False, unique=False)
	filetemplate = models.CharField(max_length=64, blank=False, unique=False)
	def get_label (self):
		return self.filename
	def __str__(self):
		return self.filename
	class Meta:
		verbose_name_plural = "Deliverables"

app/preport/templates/reports/report_add.html
{% extends 'home/template.html' %}
{% load i18n %}
{% load bleach_tags %}

{% block title %} {% translate "Reports" %} {% endblock title %}

{% block stylesheets %}
  {{ block.super }}

  <link rel="stylesheet" href="/static/plugins/daterangepicker/daterangepicker.css" />
  <link rel="stylesheet" href="/static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">

{% endblock stylesheets %}

{% block content %}


<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>{% translate "Reports" %}</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/">{% translate "Home" %}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'report_list' %}">{% translate "Reports" %}</a></li>
          <li class="breadcrumb-item active">{% translate "Add or Edit Report" %}</li>
        </ol>
      </div>
    </div>
  </div>
</section>


<section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">

            <div class="card card-outline card-success">
              <div class="card-header">
                <h3 class="card-title">{% translate "Report details" %}</h3>
              </div>
              
              <form role="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">{% translate "Product" %}</label>
                      <div class="col-md-10 col-sm-10 col-xs-12">
                        {{ form.product }}
                      </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">{% translate "Report ID" %}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                      {{ form.report_id }}
                    </div>
                  </div>
   
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">{% translate "Report Title" %}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                      {{ form.title }}
                    </div>
                  </div>

                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">{% translate "Executive summary" %}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                      {{ form.executive_summary }}
                    </div>
                  </div>

                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">{% translate "Scope" %}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                      {{ form.scope }}
                    </div>
                  </div>

                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">{% translate "Out of scope" %}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                      {{ form.outofscope }}
                    </div>
                  </div>

                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">{% translate "Methodology" %}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                      {{ form.methodology }}
                    </div>
                  </div>

                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">{% translate "Recommendation" %}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                      {{ form.recommendation }}
                    </div>
                  </div>


                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">{% translate "Report date" %}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="far fa-calendar-alt"></i>
                          </span>
                        </div>
                        {{ form.report_date }}
                      </div>
                    </div>
                  </div>


                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">{% translate "Audit dates" %}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="far fa-calendar-alt"></i>
                          </span>
                        </div>
                        {{ form.audit }}
                      </div>
                    </div>
                  </div>


                </div>


                {% if form.errors %}
                   {% for field in form %}
                       {% for error in field.errors %} 
                          <div class="container">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                              <div class="alert alert-danger alert-dismissible ">
                              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                              <h5><i class="icon fas fa-ban"></i> Error</h5>
                              {{ field.name }}: {{ error|escape }}
                              </div>
                            </div>
                          </div>
                       {% endfor %}
                   {% endfor %}
                {% endif %}
                
                <div class="card-footer">
                  <button type="submit" class="btn btn-success">{% translate "Save Report" %}</button>
                </div>
              </form>
            </div>


        </div>
      </div>
    </div>
</section>


{% endblock content %}


{% block javascripts %}
  {{ block.super }}

<script src="/static/plugins/moment/moment.min.js"></script>
<script src="/static/plugins/inputmask/jquery.inputmask.min.js"></script>
<script src="/static/plugins/daterangepicker/daterangepicker.js"></script>
<script src="/static/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>

<script>
  $(function () {
    //Date range picker
    $('#audit').daterangepicker({
      locale: {
        format: 'YYYY-MM-DD'
      }
    });

    //Date picker
    $('#reportdate').datetimepicker({
        format: 'L'
    });

  })
</script>

{% endblock javascripts %}

app/preport/templates/reports/report_list.html
{% extends 'home/template.html' %}
{% load i18n %}
{% load bleach_tags %}

{% load app_filters %}

{% block title %} {% translate "Report List" %} {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}

    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{% translate "Report List" %}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">{% translate "Home" %}</a></li>
              <li class="breadcrumb-item active">{% translate "Reports" %}</li>
            </ol>
          </div>
        </div>
      </div>
    </section>

    <section class="content">

    <div class="container-fluid">
      <div class="card card-outline card-primary">
        <div class="card-header">
          <h3 class="card-title">{{ DB_report_query.count }} Report{{ DB_report_query.count|pluralize:"" }}</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          <table id="reportlist" class="table table-bordered table-hover">
              <thead>
                  <tr>
                    <th style="width: 18%" class="text-center">{% translate "ID" %}</th>
                    <th style="width: 25%" class="text-center">{% translate "Report" %}</th>
                    <th style="width: 10%" class="text-center">{% translate "Customer" %}</th>
                    <th style="width: 12%" class="text-center">{% translate "Product" %}</th>
                    <th style="width: 12%" class="text-center">{% translate "Findings" %}</th>
                    <th style="width: 22%" class="text-center">{% translate "Actions" %}</th>
                  </tr>
              </thead>
              <tbody>

              {% for report in DB_report_query %}
                  <tr>
                    <td>{{ report.report_id }} </td>
                    <td>{{ report.title }} </td>
                    <td><a href="{% url 'customer_view' report.product.customer.pk %}">{{ report.product.customer.name }}</a></td>
                    <td>{{ report.product.name }} </td>
                    <td>
                      <span class="pull-right badge bg-red">{{ report.db_finding_set.count }}</span> {% translate "Finding" %}{{ report.db_finding_set.count|pluralize:"" }}
                    </td>
                    <td class="text-center">
                        <a href="/report/view/{{ report.pk }}"><button type="button" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> {% translate "View" %}</button></a>
                        
                        {% if user.groups.all.0|stringformat:'s' == "administrator" %}

                          <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target=".mm-modal-clone-{{report.pk}}"><i class="fas fa-copy"></i> {% translate "Clone" %} </button>

                          <a href="/report/edit/{{ report.pk }}"><button type="button" class="btn btn-info btn-sm"><i class="fa fa-edit"></i> {% translate "Edit" %}</button></a> 
                          <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target=".mm-modal-{{report.pk}}"><i class="fas fa-trash"></i> {% translate "Delete" %} </button>
                        {% endif %}
                    </td>
                  </tr>
                  

                        <div class="modal modal-danger fade mm-modal-{{report.pk}}" id="modal-danger">
                          <div class="modal-dialog">
                            <div class="modal-content bg-danger">
                              <div class="modal-header">
                                <h4 class="modal-title">{% translate "Are you sure?" %}</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                <p>{% translate "Delete Report" %}&hellip;</p>
                              </div>
                              <div class="modal-footer justify-content-between">
                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">{% translate "Close" %}</button>
                                <button type="button" onclick="DeleteID({{report.pk}});" class="btn btn-outline-light">{% translate "Delete Report" %}</button>

                              </div>
                            </div>
                          </div>
                        </div>



                        <div class="modal modal-warning fade mm-modal-clone-{{report.pk}}" id="modal-warning">
                          <div class="modal-dialog">
                            <div class="modal-content bg-warning">
                              <div class="modal-header">
                                <h4 class="modal-title">{% translate "Are you sure?" %}</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                <p>{% translate "Clone Report and Findings" %}&hellip;</p>
                              </div>
                              <div class="modal-footer justify-content-between">
                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">{% translate "Close" %}</button>
                                <button type="button" onclick="DuplicateID({{report.pk}});" class="btn btn-outline-light">{% translate "Clone Report and Findings" %}</button>
                              </div>
                            </div>
                          </div>
                        </div>



                {% endfor %}

              </tbody>
          </table>
        </div>
       
      </div>
      
    </div>
  </section>



{% endblock content %}

{% block javascripts %}
  {{ block.super }}

<script>
  $(function () {
    $("#reportlist").DataTable({
      "paging": true,
      "searching": true,
      "responsive": true, 
      "lengthChange": false, 
      "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#reportlist_wrapper .col-md-6:eq(0)');
  });
</script>

<script>
  function DeleteID(del_id) {
        $.ajax({
            type: 'POST',
            url: "/en/report/delete/",
            headers:{
              "X-CSRFToken": '{{ csrf_token }}'
            },
            data : { 'delete_id': del_id},

            success : function(json) {
              document.location.href = "{% url 'report_list' %}";
            }
        })
  }

  function DuplicateID(dup_id) {
    $.ajax({
        type: 'POST',
        url: "{% url 'report_findings_duplicate' %}",
        headers:{
          "X-CSRFToken": '{{ csrf_token }}'
        },
        data : { 'duplicate_id': dup_id},

        success : function(json) {
          document.location.href = "{% url 'report_list' %}";
        }
    })
  }

</script>

{% endblock javascripts %}